config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get '/portfolio' => 'pages#portfolio'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1><%= link_to 'Rosalie Chan', root_path %></h1>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><a href="/about/">About</a></li>
            <li><a href="/blog/">Blog</a></li>
            <li><%= link_to 'Work', portfolio_path %></li>
						<li><a href="/contact/">Contact</a></li> 
          </ul>
        </div><!--/.nav-collapse -->
      </div>
      </nav>
  </header>

<%= yield %>

</body>
</html>

app/views/pages/portfolio.html.erb
   	<h3 style="position:relative; bottom:80px">Below are examples of my work in HTML/CSS/JavaScript/jQuery, as well as other design projects I have worked on.  For design, I use Adobe InDesign, PhotoShop and Illustrator.</h3>
   	<br></br>
   	<h4><a href="http://www.northbynorthwestern.com/">North by Northwestern</a></h4>
   	<ul>
   	<li><a href="http://www.northbynorthwestern.com/story/a-day-on-a-film-set/"><img src="rtvf.png"></a></li>
   	<li><a href="http://apps.northbynorthwestern.com/hungry/timeline/"><img src="timeline.png"></a></li>
   	<li><a href="http://www.northbynorthwestern.com/story/tips-and-tricks-for-dillo-day/"><img src="madlibs.png"></a></li>
   	<li><a href="http://apps.northbynorthwestern.com/magazine/2015/spring/march-madness/"><img src="bball.png"></a></li>
   	<li><a href="http://apps.northbynorthwestern.com/magazine/2015/spring/zaramela/"><img src="band.png"></a></li>
   	<li><a href="http://apps.northbynorthwestern.com/magazine/2015/spring/toby-jugs/"><img src="jugs.png"></a></li>
   	<li><a href="http://apps.northbynorthwestern.com/magazine/2015/spring/nu-divest/"><img src="divest.png"></a></li>
   	<li><a href="http://apps.northbynorthwestern.com/homeless/"><img src="homeless.png"></a></li>
   	<li><a href="http://www.northbynorthwestern.com/story/ask-me-about/"><img src="ask.png"></a></li>
   	<li><a href="http://apps.northbynorthwestern.com/submerged/"><img src="submerged.png"></a></li>
	</ul>
	
	<h4>Mochi Magazine</h4>
	<ul>
	<li><a href="http://www.mochimag.com/article/mochis-25-game-changers-under-25"><img src="mochi.png"></a></li>
	</ul>
	
	<h4>Innovation in Journalism and Technology</h4>
		<ul>
	<li><a href="https://medium.com/@RosalieChan17/wiki-studio-5bbc0b395625"><img src="wiki.png"></a></li>
	</ul>
   

app/views/pages/welcome.html.erb
<main>
  <h3>Hi, my name is Rosalie Chan. I am a journalism and computer science student at Northwestern University.</h3>
  <center><button><%= link_to 'View My Work', portfolio_path %></button></center>
</main>

<footer>
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABtElEQVRIS7WW/TEEQRDF30VABlwEyIAIEAEi4CJABGSACLgIEIG7CBABIqB+W9NXbXTPLlf6r63dnvf643XPjtS2dUm7krYl8bxZ3GeSXiQ9SJqW5xBplOADdirpsCcA+3wt6Twiigj2JF1JWh0Ibm7vko4k3flzNQERA76MQUJGnXkCIr9dBtmd3bdMjICaP/2hLFk8lGuLnhgBKR38Ivq5qzWZb0h6lbTmMG4QCQRE/1yBA3CZ9OOxyNYfQb5I+aLCGUNwEnwwEKIjuxV3cKfov04YAnro1TeBAFkxTN4YonF5wQGIUBiRZvKl7j4Qjk8hYCqpoTfqeebl1tMfSN8CnxkEn9GHooKhfac895FzRoDvt4HpYUIQxxlBVCJ8KRN1Z6G1jPKgwqg386zJBriYyAZDGr01OZKpx0OmE0mopLa+3dXJNBs0ACkfESLb2lAZK71l3aBh9aoAHGAuE0jM7AIia55btlgVOOEMUD0oPRjp548ylItlh+e/rmsLpa9pQzJKLxw7HC24IcCUhQCbV6ZvJioZekfQUPx/qC37q/BEZGS/LbYUuS/st4WIIxl3GF98TFw2dxh7nQAAAABJRU5ErkJggg=="/>
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAByUlEQVRIS62VgTUDURBFXyqgA9IBFUgqQAWkAlSACkgFqEBSgaQCOhAVkAo4d8+fPWPM7soy5/yTtf6+N/Pe/PkDdceepANJu5J4Jl4krSQty3MjyqAF/1TSZQFuSwOiK0kP2aaMgEzvJI26i/u2YyFpUiqr/xEJkOBJ0vaG4Lb9Q9LYy+YJ/gqekhgBGT87veeS7iUdSTrpqAbtZ5Lw7NA1wT7PRoBJGGpxIem2/EFlLMxkEfjEoptYxLmkG4dxjfkQkP1r0N0T/NaOSIAfQwgoja7x8R8E4E0gQD/TjpdvRRIy2CRQArl23EdzCNDVv6y02wTZ7Y1eriD4DGAcFjqoT/yQOyPoo78lEyuo2jRWMC0t16cCWvvMfbiGgBnCtLTAk2Ef9MTPJQSRFew+MsVzAM4UAqYmAy4GetJRXUF7IkvWeWMbFSYTm7hEOBtbkjgLPDOb+PVBxyAt8yqbvuCMjMBXgTwcGF/VcUIA8GNLeYzthR/X5kU1Q8pphhjTs3NB1u8NBHUnxgvHpOLXKmnzILY4e5GT6qrIrkyyjXdA090dCbgb8KaOpg/ZhGQY3ZQI741gXYBjI6QVGDsaU6qtTCoAWY2z6wsxXGWWjqmNhAAAAABJRU5ErkJggg=="/>
  <br>
  <p>&copy; Rosalie Chan</p>